"""rename address

Revision ID: 291dc811c872
Revises: 62904eef213d
Create Date: 2024-07-03 22:15:40.890528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291dc811c872'
down_revision = '62904eef213d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address',new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
